import type { MonitoringDefinition } from "./types";

const CATALOG_TIMESTAMP = "2026-07-21T00:00:00.000Z";

export const DEFAULT_MONITORING_DEFINITIONS: MonitoringDefinition[] = [
  {
    campaignId: "test_inssa_safe",
    createdAt: CATALOG_TIMESTAMP,
    enabled: true,
    environment: "staging",
    evidencePolicy: "always",
    id: "a94cd531-bb89-4eeb-a68e-c7f77f61d219",
    name: "INSSA Safe Regression Observation",
    notificationPolicy: "warning",
    product: "INSSA",
    retryPolicy: { backoffMs: 60_000, maxAttempts: 2 },
    runPolicy: "one_active_run",
    schedule: null,
    schemaVersion: 1,
    severity: "medium",
    timeout: 600_000,
    triggerType: "manual",
    updatedAt: CATALOG_TIMESTAMP
  },
  {
    campaignId: "test_inssa_campaign_security",
    createdAt: CATALOG_TIMESTAMP,
    enabled: false,
    environment: "staging",
    evidencePolicy: "always",
    id: "cc5edfe2-5452-4437-a532-d14101fd1c2d",
    name: "INSSA Security Campaign Observation",
    notificationPolicy: "critical",
    product: "INSSA",
    retryPolicy: { backoffMs: 120_000, maxAttempts: 1 },
    runPolicy: "queue",
    schedule: null,
    schemaVersion: 1,
    severity: "high",
    timeout: 900_000,
    triggerType: "deployment",
    updatedAt: CATALOG_TIMESTAMP
  },
  {
    campaignId: "test_inssa_campaign_security_verify",
    createdAt: CATALOG_TIMESTAMP,
    enabled: false,
    environment: "staging",
    evidencePolicy: "on_failure",
    id: "fc38c819-f4f8-478f-bc45-67c8c9be464a",
    name: "INSSA Security Verification Observation",
    notificationPolicy: "info",
    product: "INSSA",
    retryPolicy: { backoffMs: 60_000, maxAttempts: 2 },
    runPolicy: "skip",
    schedule: null,
    schemaVersion: 1,
    severity: "medium",
    timeout: 600_000,
    triggerType: "api",
    updatedAt: CATALOG_TIMESTAMP
  },
  {
    campaignId: "test_inssa_safe",
    createdAt: CATALOG_TIMESTAMP,
    enabled: true,
    environment: "staging",
    evidencePolicy: "always",
    id: "17ab8e2e-f129-479c-a68e-c2087c1c52d0",
    name: "INSSA Daily Safe Regression",
    notificationPolicy: "warning",
    product: "INSSA",
    retryPolicy: { backoffMs: 60_000, maxAttempts: 2 },
    runPolicy: "one_active_run",
    schedule: { frequency: "daily", hour: 3, minute: 0, timezone: "Europe/Dublin" },
    schemaVersion: 1,
    severity: "medium",
    timeout: 600_000,
    triggerType: "schedule",
    updatedAt: CATALOG_TIMESTAMP
  },
  {
    campaignId: "monitor_inssa_auth_staging",
    createdAt: CATALOG_TIMESTAMP,
    enabled: true,
    environment: "staging",
    evidencePolicy: "always",
    id: "9e678cef-036a-46b9-a6ca-f25ad880e92a",
    name: "INSSA Authentication Monitoring - Staging Midday",
    notificationPolicy: "critical",
    product: "INSSA",
    retryPolicy: { backoffMs: 60_000, maxAttempts: 2 },
    runPolicy: "one_active_run",
    schedule: { frequency: "daily", hour: 12, minute: 0, timezone: "Europe/Dublin" },
    schemaVersion: 1,
    severity: "critical",
    timeout: 120_000,
    triggerType: "schedule",
    updatedAt: CATALOG_TIMESTAMP
  },
  {
    campaignId: "monitor_inssa_auth_staging",
    createdAt: CATALOG_TIMESTAMP,
    enabled: true,
    environment: "staging",
    evidencePolicy: "always",
    id: "3080f13e-022a-44a1-bbbb-b905468ca18a",
    name: "INSSA Authentication Monitoring - Staging Evening",
    notificationPolicy: "critical",
    product: "INSSA",
    retryPolicy: { backoffMs: 60_000, maxAttempts: 2 },
    runPolicy: "one_active_run",
    schedule: { frequency: "daily", hour: 18, minute: 0, timezone: "Europe/Dublin" },
    schemaVersion: 1,
    severity: "critical",
    timeout: 120_000,
    triggerType: "schedule",
    updatedAt: CATALOG_TIMESTAMP
  },
  {
    campaignId: "monitor_inssa_auth_production",
    createdAt: CATALOG_TIMESTAMP,
    enabled: false,
    environment: "production",
    evidencePolicy: "always",
    id: "ab90fa94-369f-4835-8942-465a50fd1dc6",
    name: "INSSA Authentication Monitoring - Production Midday",
    notificationPolicy: "critical",
    product: "INSSA",
    retryPolicy: { backoffMs: 60_000, maxAttempts: 2 },
    runPolicy: "one_active_run",
    schedule: { frequency: "daily", hour: 12, minute: 0, timezone: "Europe/Dublin" },
    schemaVersion: 1,
    severity: "critical",
    timeout: 120_000,
    triggerType: "schedule",
    updatedAt: CATALOG_TIMESTAMP
  },
  {
    campaignId: "monitor_inssa_auth_production",
    createdAt: CATALOG_TIMESTAMP,
    enabled: false,
    environment: "production",
    evidencePolicy: "always",
    id: "e663f90b-b4c8-42e8-b1c4-23403312fa49",
    name: "INSSA Authentication Monitoring - Production Evening",
    notificationPolicy: "critical",
    product: "INSSA",
    retryPolicy: { backoffMs: 60_000, maxAttempts: 2 },
    runPolicy: "one_active_run",
    schedule: { frequency: "daily", hour: 18, minute: 0, timezone: "Europe/Dublin" },
    schemaVersion: 1,
    severity: "critical",
    timeout: 120_000,
    triggerType: "schedule",
    updatedAt: CATALOG_TIMESTAMP
  }
];
